### PR TITLE
[Feature] - Wait for initialization before calling methods

### PR DESCRIPTION
**Pull request by ecwyne**
## Current Behavior

```javascript
// hydra.js
import hydra from 'hydra'

hydra.init({...})

export default hydra;
```
```javascript
// service.js
import hydra from './hydra.js';
hydra.getServices()
    .then(...)
    .catch(...); // Throws 'No Redis Connection'

hydra.makeAPIRequest({...})
    .then(...)
    .catch(...); // Throws 'Cannot read property 'keys' of null (this.redisdb)'
```

## New Behavior
Methods that return promises can wait for initialization to complete before processing. Or alert the end user that `hydra.init()` was never invoked.

```javascript
import hydra from 'hydra';

hydra.init({...});

hydra.getServices()
    .then(...) // WORKS!
    .catch(...);

hydra.makeAPIRequest({...})
    .then(...) // WORKS!
    .catch(...);
```

```javascript
import hydra from 'hydra';

hydra.getServices()
    .then(...)
    .catch(...); // throws 'You must call hydra.init() before invoking hydra.getServices()'

hydra.makeAPIRequest({...})
    .then(...)
    .catch(...); // throws 'You must call hydra.init() before invoking hydra.makeAPIRequest()'
```

### CODE REVIEW

**Comment by cjus** [comment]
@ecwyne thanks for the PR. We'll review.

**Comment by cjus** [comment]
@ecwyne The expected behavior in Hydra and HydraExpress is that no use of hydra should be made until it's fully initialized - that is, the `hydra.init` promise is resolved. As in this example in hydra-router:

https://github.com/flywheelsports/hydra-router/blob/master/hydra-router.js#L88

While that behavior can be patched as you've shown - it's reasonable to expect that that hydra should not be used until it's successfully initialized. The pattern you've shared would have to be maintained throughout the emerging code base just to protect against a misunderstanding of when it's safe to use Hydra during initialization.  Seems that can be handled with improved documentation.

@emadum please review as well and @ecwyne please feel free to press this if you feel I'm missing something. Thanks for your involvement with Hydra and in helping to raise issues - that's exactly what the project needs!

**Comment by emadum** [comment]
@cjus I do think @ecwyne's error messages about needing to call hydra.init first are much better than `No Redis Connection` or `Cannot read property 'keys' of null (this.redisdb)`. After a quick glance at the current code, we already have a `this.initialized` boolean that we check in `_getServiceName` and `_registerService` but not `getServices` or `makeAPIRequest`. I like the consistency that @ecwyne's PR would introduce.

But I'm also not a fan of boilerplate code like that. What about monkey-patching the Hydra object? 
E.g. something like this in the Hydra constructor:

```javascript
Object.keys(this)
  .filter(prop => prop.substr(0,1) !== '_' && prop !== 'init' && typeof this[prop] === 'function')
  .forEach(method => {
    let oldMethod = this[method];
    this[method] = (...args) => {
      if (!this.initialized) {
        throw new Error('init() not called, Hydra requires a configuration object.');
      }
      oldMethod.apply(this, args);
    }
  });
```

Although this may just be trading boilerplate for [magic](https://en.wikipedia.org/wiki/Magic_(programming)).

**Comment by ecwyne** [comment]
Thanks for your thoughts @cjus @emadum!

I do see in the docs and examples that the hydra object is not expected to be used until initialization has completed. The issue I was having was similar to my first example where I encapsulate all of my hydra initialization in a separate module (because I then use it in multiple places)

```javascript
// hydra.js
import hydra from 'hydra'

hydra.init({...})

export default hydra;
```
```javascript
// service.js
import hydra from './hydra.js';

// How can I wait for init to complete??
```
### Option 1: use setInterval
```
// service.js
const i = setInterval(() => {
  if (hydra. initialized){
    ... (do stuff with hydra)
    clearInterval(i);
  } 
}, 200)
```

### Option 2 Export patched functions from hydra.js
This is currently what I have running in my project.
```javascript
// hydra.js
import hydra from 'hydra';

const init = hydra.init({...})
		.then(() => console.log('Hydra configured'))
		.catch(() => console.log('Hydra Error'));

export const makeAPIRequest = msg => init.then(() => {
  const message = hydra.createUMFMessage(msg);
  return hydra.makeAPIRequest(message);
}));
```

```javascript
// service.js
import {makeAPIRequest} from './hydra.js';
// or
import * as hydra from './hydra.js';

makeAPIRequest({...}).then(...)
```

### Option 3 export the init promise
```javascript
// hydra.js
import hydra from 'hydra';

export const init = hydra.init({...});
export default hydra;
```

```javascript
// service.js
import hydra, {init} from './hydra.js';

init.then(() => {
  ... (do stuff with hydra)
});
```

> In short, Hydra lowers the barriers to entry for building and deploying microservices.

While option 3 seems to be the best to me, none of these options are terribly easy to follow or implement for new developers. Especially ones who are unfamiliar with asynchronous javascript. This also requires the users of the library to be disciplined in checking for initialization every time they use hydra.

If maintainability within the hydra library is a concern. Maybe the wrapping of methods with `ensureInit` can be done automatically (somewhat) like the example "monkey patch" code that @emadum  suggested

**Comment by ecwyne** [comment]
Like this

```javascript
const methodsRequiringInit = ['getServices', 'makeAPIRequest', 'sendMessage', ...etc];
methodsRequiringInit.forEach(methodName => {
  const oldMethod = this[methodName];
  this[methodName] = (...args) => this.ensureInit(methodName).then(() => oldMethod.apply(this, args));
});
```

@emadum I believe we would need to select the methods to wrap manually because not all methods require `hydra.init` before execution (eg. `hydra.createUMFMessage`)

**Comment by cjus** [comment]
@emadum really good point on the trade-off between boilerplate and magic.  
@ecwyne would having Hydra emit an event on initialization-complete address your need for handling post initialization concerns from another module?

As you can see from the Hydra source code, Hydra is derived from Node `EventEmitter`. Hydra already emits events for incoming messages and log writes. If we added events for initialization then you could do this - ala jQuery.

```javascript
hydra.on('ready', () => {
})
```

**Comment by ecwyne** [comment]
@cjus That's an interesting alternative for sure. My only concern would be that the event listener (`hydra.on('ready')`) would need to be set up BEFORE the ready event fired. Consider the following example.

```javascript
import hydra from './hydra.js';
router.get('/ping', (req, res) => {
  hydra.makeAPIRequest({...}).then(...); // option "A"
  // or
  hydra.on('ready', () => hydra.makeAPIRequest({...}).then(...)); // option "B"
});
```
|                                    | Option "A"   | Option "B"   |
|------------------------------------|--------------|--------------|
| Request comes BEFORE init finishes | Throws Error | Works        |
| Request comes AFTER init finishes  | Works        | Never runs |

**Comment by ecwyne** [comment]
Another option would be to have a `hydra.ready()` method that returns the promise returned by `hydra.init({...});` (Essentially what I called `ensureInit` in the PR)

```javascript
import hydra from './hydra.js';

hydra.ready().then(() => ...); // works

request.get('/ping', (req, res) => {
  hydra.ready().then(() => ...); //works
});
```

**Comment by cjus** [comment]
@ecwyne that I could live with. For two reasons:

* I see the split module use-case as an edge case. 
* additional boilerplate would only be necessary in split module cases. 

I do realize that what I call "edge case" will include hydra plugins. But I would be ok with that as we're hoping for more hydra users than plugin authors.

**Comment by ecwyne** [comment]
@cjus I've updated the PR to reflect this change.

1. I'm happy to create a new PR if you would like a cleaner commit log.
2. I'm happy to update any necessary documentation if you'd like.

**Comment by cjus** [comment]
@ecwyne #1 and #2 would be great.  For the docs portion please submit a gist that we can use at https://www.hydramicroservice.com

**Comment by ecwyne** [comment]
@cjus is the source for https://www.hydramicroservice.com published anywhere so that I can see how it's formatted?

**Comment by cjus** [comment]
@ecwyne it's markdown.

**Comment by ecwyne** [comment]
@cjus I've cleaned up the commit history on this PR.

I picture this [gist](https://gist.github.com/ecwyne/9b49a42cbdf835c9c8b9d7f3f6fa0526) can be added to https://www.hydramicroservice.com/docs/hydra-core/hydra-methods.html in the "Setup" section. 

I'm not sure where else I should add documentation apart from changing some examples from
```javascript
hydra.init({...}).then(...);
```
to
```javascript
hydra.init({...});
hydra.ready().then(...);
```

**Comment by cjus** [comment]
@ecwyne on the documentation I was thinking along the lines of why and where someone might want to use the `.ready()` call.

**Comment by ecwyne** [comment]
@cjus I've updated the gist with some more details about when you might use `hydra.ready()`

https://gist.github.com/ecwyne/9b49a42cbdf835c9c8b9d7f3f6fa0526

**Comment by cjus** [comment]
@emadum Can you review this in the context of HydraExpress?

**Comment by cjus** [comment]
@ecwyne please rebase

**Comment by ecwyne** [comment]
@cjus should be good to go now

**Comment by cjus** [comment]
@ecwyne thanks. Just want to give @emadum an opportunity to review this one. He was traveling on business last week. He's back with us on Monday.

**Comment by cjus** [comment]
@ecwyne Documentation added:

* https://www.hydramicroservice.com/docs/hydra-core/hydra-methods.html
* https://www.hydramicroservice.com/docs/hydra-core/getting-started.html

**Pull request merged**
